# Generated by Django 5.1.1 on 2024-10-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
